CDH-67407: SolrCellMorphlineTest broke starting April 11
The bouncy castle provider jar had a security issue which led CDH-40881 to upgrade the jar to bcprov-jdk15on version 1.59 (parent JIRA is . It turns out that this new bouncy castle jar isn't runtime compatible with Pkcs7Parser.java of tika-1.16 anymore, as now org.kitesdk.morphline.solrcell.SolrCellMorphlineTest.testSolrCellDocumentTypes errors out with:

org.kitesdk.morphline.api.MorphlineCompilationException: Cannot instantiate Tika parser: org.apache.tika.parser.crypto.Pkcs7Parser

...

Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/operator/OperatorCreationException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.kitesdk.morphline.solrcell.SolrCellBuilder$SolrCell.<init>(SolrCellBuilder.java:173)
	... 50 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.operator.OperatorCreationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 53 more

Nothing in morphlines uses Pkcs7Parser directly or indirectly so the workaround is to simply remove Pkcs7Parser from the test. Also see the corresponding discussion about this in the parent JIRA CDH-40741

Change-Id: I116496b479e2f1bc9ca6b49b0229212e49cbe6e1